version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    volumes:
      - $PWD/logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5005:5000"
    links:
      - elasticsearch
      - rabbitmq

  kibana:
    image: kibana:7.1.1
#    build: kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  rabbitmq:
    build: rabbitmq/
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
